p.vostretsov/ConcurrentMutatorsRecording
skbkontur/GrobExp.Mutators pull request #2
Opened 2018-10-02 06:07 UTC by fakefeik

2018-10-02 07:48 UTC, Anton92nd requested changes

2018-10-02 07:48 UTC, Anton92nd commented on Mutators/MutatorsRecording/RecordNode.cs
> -        public RecordNode(string name, string parentFullName, bool isExcludedFromCovreage = false)
Понятно, что у CompareExchange нет перегрузки для bool, но это не повод менять интерфейс этого класса. Можно же внутри класса конвертнуть bool в int.

2018-10-02 07:48 UTC, Anton92nd commented on Mutators/MutatorsRecording/RecordNode.cs
>                  node.RecordCompilingExpression(pathComponents.GetRange(1, pathComponents.Count - 1), value, isExcludedFromCoverage);
Переписать бы еще поэффективней: получать IEnumerable<string> и формировать дерево через .Any() и Skip(1) или вообще без рекурсии через цикл.

2018-10-02 07:48 UTC, Anton92nd commented on Mutators/ConverterCollection.cs
> +            var converterType = configurator.Root.ConverterType;
Мы же внутри класса ConverterCollection<TSource, TDest>, можно просто GetType() использовать.

2018-10-02 07:48 UTC, Anton92nd commented on Mutators/ConverterConfigurator.cs
> +        public ModelConfigurationNode Root { get; }
Давай оставим его internal

2018-10-02 07:48 UTC, Anton92nd commented on Mutators/ConverterCollection.cs
> +                        configurator.SetMutator(Expression.Property(pathToTarget, "TypeCode"), EqualsToConfiguration.Create<TDest>(GetType(), Expression.Lambda(Expression.Constant(TypeCode.Object))))
Тут заиспользовать converterType

2018-10-02 07:48 UTC, Anton92nd commented on Mutators/ConverterConfigurator.cs
> +        public ModelConfigurationNode Root { get; }
Этого тоже internal

2018-10-02 07:48 UTC, Anton92nd commented on Mutators/DataConfiguratorCollectionBase.cs
> +                        var root = ModelConfigurationNode.CreateRoot(GetType(), typeof(TData));
Так, значит нас не только конвертеры интересуют, а валидаторы тоже. Давай в ModelConfigurationNode обзовём его не ConverterType, а ConfiguratorType.

2018-10-02 07:48 UTC, Anton92nd commented on Mutators/DataConfiguratorCollectionBase.cs
> +                        var root = ModelConfigurationNode.CreateRoot(GetType(), typeof(TData));
В контексте конвертеров по-прежнему можно параметры называть converterType

2018-10-02 07:48 UTC, Anton92nd commented on Mutators/MutatorsConfigurator.cs
> +        public ModelConfigurationNode Root { get; }
Тоже internal

2018-10-02 07:48 UTC, Anton92nd commented on Mutators/MutatorsTree.cs
> +            var migratedTree = ModelConfigurationNode.CreateRoot(converterTree.ConverterType, typeof(T));
А вот это интересный момент. Надо поразмыслить правильно ли это.

2018-10-02 07:48 UTC, Anton92nd commented on Mutators/Visitors/CompositionPerformer.cs
> +                var mutator = (EqualsToConfiguration)setters[index];
Давай в строке 333 вместо Where сделаем OfType

2018-10-02 07:48 UTC, Anton92nd commented on Mutators/Visitors/CompositionPerformer.cs
> +                    var equalsToConfiguration = mutator;
inline variable

2018-10-02 07:48 UTC, Anton92nd commented on Mutators/ModelConfigurationNode.cs
> +        public Type ConverterType { get; }
Тоже internal. Переименовать в ConfiguratorType

2018-10-02 07:49 UTC, fakefeik commented on Mutators/MutatorsRecording/RecordNode.cs
> -        public RecordNode(string name, string parentFullName, bool isExcludedFromCovreage = false)
снаружи класса конструктор вызывается лишь один раз, мне показалось, что лучше пофиксить там

2018-10-02 07:50 UTC, fakefeik commented on Mutators/ConverterCollection.cs
> +            var converterType = configurator.Root.ConverterType;
он же вроде медленнее чем просто свойство получить, которое уже засечено?

2018-10-02 07:55 UTC, Anton92nd commented on Mutators/MutatorsRecording/RecordNode.cs
> -        public RecordNode(string name, string parentFullName, bool isExcludedFromCovreage = false)
Ну тип инкапсуляция, все дела. По логике использования это бул ведь.

2018-10-02 07:56 UTC, Anton92nd commented on Mutators/ConverterCollection.cs
> +            var converterType = configurator.Root.ConverterType;
Ну в целом пофиг, мне показалось так прозрачнее будет. Хотя в этом варианте понятно, что всё из одного места берётся. Давай так оставим.

2018-10-02 12:26 UTC, fakefeik commented on Mutators/MutatorsRecording/RecordNode.cs
> -        public RecordNode(string name, string parentFullName, bool isExcludedFromCovreage = false)
поправил

2018-10-02 12:26 UTC, fakefeik commented on Mutators/ConverterConfigurator.cs
> +        public ModelConfigurationNode Root { get; }
поправил

2018-10-02 12:27 UTC, fakefeik commented on Mutators/ConverterCollection.cs
> +                        configurator.SetMutator(Expression.Property(pathToTarget, "TypeCode"), EqualsToConfiguration.Create<TDest>(GetType(), Expression.Lambda(Expression.Constant(TypeCode.Object))))
поправил

2018-10-02 12:27 UTC, fakefeik commented on Mutators/ConverterConfigurator.cs
> +        public ModelConfigurationNode Root { get; }
поправил

2018-10-02 12:27 UTC, fakefeik commented on Mutators/DataConfiguratorCollectionBase.cs
> +                        var root = ModelConfigurationNode.CreateRoot(GetType(), typeof(TData));
поправил

2018-10-02 12:27 UTC, fakefeik commented on Mutators/MutatorsConfigurator.cs
> +        public ModelConfigurationNode Root { get; }
поправил

2018-10-02 12:27 UTC, fakefeik commented on Mutators/Visitors/CompositionPerformer.cs
> +                var mutator = (EqualsToConfiguration)setters[index];
поправил

2018-10-02 12:27 UTC, fakefeik commented on Mutators/Visitors/CompositionPerformer.cs
> +                    var equalsToConfiguration = mutator;
поправил

2018-10-02 12:27 UTC, fakefeik commented on Mutators/ModelConfigurationNode.cs
> +        public Type ConverterType { get; }
поправил

2018-10-02 13:43 UTC, Anton92nd requested changes

2018-10-02 13:43 UTC, Anton92nd commented on Mutators/ModelConfiguration/TreeValidatorBuilder.cs
> -            root.BuildValidator(pathFormatter, node == node.Root ? null : node, aliases, new Dictionary<ParameterExpression, ExpressionPathsBuilder.SinglePaths>(), result, treeRootType, priority, val
А че, зачем эти изменения?

2018-10-02 13:43 UTC, Anton92nd commented on Mutators/MutatorsRecording/RecordNode.cs
> +            if (!isExcludedFromCoverage)
Я чет не понимаю, зачем весь этот огород. У нас изначально это поле может быть true, но если изменилось на false, то вроде как всегда false. Не совсем понимаю зачем вообще относительно него примитивы синхронизации. Если параметр false, то надо в поле false присвоить. Присовение атомарное, с ним всё ок.

2018-10-03 05:12 UTC, fakefeik commented on Mutators/ModelConfiguration/TreeValidatorBuilder.cs
> -            root.BuildValidator(pathFormatter, node == node.Root ? null : node, aliases, new Dictionary<ParameterExpression, ExpressionPathsBuilder.SinglePaths>(), result, treeRootType, priority, val
попытка пофиксить нулреф при вызове `node.ConverterType`

2018-10-03 05:16 UTC, fakefeik commented on Mutators/MutatorsRecording/RecordNode.cs
> +            if (!isExcludedFromCoverage)
поправил

2018-10-10 06:51 UTC, merged